create table testdata (
	player_id INT,
	username VARCHAR(50),
	level INT,
	score INT,
	game_duration INT,
	character_class VARCHAR(7),
	inventory VARCHAR(50),
	achievements VARCHAR(50),
	guild VARCHAR(6)
);
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (1, 'kgley0', 99, 111, 938, 'warrior', '[{},{},{},{}]', '[]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (2, 'bhousin1', 96, 9816, 2483, 'warrior', '[{}]', '[]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (3, 'gpettersen2', 10, 1983, 630, 'archer', '[{}]', '[{}]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (4, 'lpagram3', 51, 8364, 1396, 'warrior', '[{},{},{}]', '[{},{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (5, 'ywilcock4', 6, 7917, 3055, 'warrior', '[{},{}]', '[{},{},{},{},{}]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (6, 'hcredland5', 11, 9592, 272, 'archer', '[{},{},{},{}]', '[{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (7, 'hkempe6', 89, 681, 824, 'mage', '[]', '[{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (8, 'jaldrin7', 32, 1417, 1285, 'warrior', '[{},{},{},{},{}]', '[]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (9, 'csteeples8', 41, 8660, 1529, 'warrior', '[{},{},{}]', '[]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (10, 'adanahar9', 88, 9463, 978, 'archer', '[{},{},{}]', '[]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (11, 'dtraysa', 1, 9426, 1309, 'archer', '[]', '[]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (12, 'dgehrickeb', 71, 3252, 851, 'mage', '[]', '[]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (13, 'ffuryc', 35, 913, 1735, 'archer', '[]', '[{},{},{}]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (14, 'gstraughand', 68, 2836, 2035, 'archer', '[{},{},{},{},{}]', '[{},{},{},{},{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (15, 'vpriddene', 47, 2597, 540, 'warrior', '[{},{},{},{},{}]', '[{},{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (16, 'kodooleyf', 83, 1326, 108, 'mage', '[{},{},{},{}]', '[{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (17, 'wluisg', 1, 1217, 3410, 'archer', '[]', '[{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (18, 'mbraundh', 1, 917, 2842, 'archer', '[]', '[]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (19, 'athumanni', 66, 3505, 633, 'warrior', '[{},{},{},{}]', '[{},{},{},{},{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (20, 'lshearmurj', 7, 2118, 402, 'warrior', '[{},{},{},{}]', '[{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (21, 'bramptonk', 86, 3202, 3254, 'warrior', '[{}]', '[{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (22, 'dregglerl', 35, 6093, 1449, 'mage', '[{},{}]', '[{},{},{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (23, 'kjandacm', 90, 8798, 1066, 'warrior', '[{},{},{}]', '[{},{},{},{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (24, 'ematashkinn', 43, 9049, 585, 'warrior', '[{},{},{},{}]', '[{},{}]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (25, 'klishmano', 51, 1409, 2238, 'warrior', '[{},{},{},{}]', '[{},{},{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (26, 'acragellp', 35, 1893, 3598, 'archer', '[]', '[{},{},{},{},{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (27, 'scicceraleq', 64, 9874, 1919, 'warrior', '[{},{}]', '[{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (28, 'hmedlenr', 21, 6807, 1493, 'mage', '[{},{},{}]', '[{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (29, 'hcarnihans', 63, 9031, 2121, 'mage', '[{},{}]', '[{},{},{},{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (30, 'mmackt', 37, 284, 152, 'warrior', '[{},{},{},{},{}]', '[{},{},{}]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (31, 'pscroggesu', 32, 4226, 465, 'archer', '[{},{},{},{}]', '[{},{},{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (32, 'bvanyakinv', 29, 4850, 2935, 'archer', '[{},{},{},{},{}]', '[]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (33, 'eminearw', 33, 8158, 176, 'archer', '[]', '[]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (34, 'bstriplingx', 97, 9513, 1739, 'archer', '[{},{},{}]', '[]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (35, 'brennelsy', 7, 3830, 1253, 'archer', '[{},{},{},{}]', '[{},{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (36, 'acoldmanz', 33, 6195, 703, 'warrior', '[{},{},{}]', '[{},{}]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (37, 'samiable10', 76, 9011, 844, 'archer', '[{},{}]', '[{},{}]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (38, 'cowttrim11', 72, 5155, 2541, 'mage', '[{},{},{},{},{}]', '[]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (39, 'tskokoe12', 5, 4442, 1803, 'warrior', '[]', '[{},{},{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (40, 'fcaldroni13', 1, 7752, 2532, 'warrior', '[{},{}]', '[]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (41, 'hdennistoun14', 9, 3764, 965, 'archer', '[{}]', '[{},{},{},{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (42, 'gcromleholme15', 66, 4021, 1946, 'archer', '[{},{},{},{},{}]', '[{},{},{},{}]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (43, 'rbullman16', 10, 2058, 2255, 'archer', '[{}]', '[]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (44, 'htesh17', 51, 1281, 1530, 'mage', '[{},{},{},{}]', '[{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (45, 'ngracey18', 64, 9495, 2310, 'mage', '[{}]', '[{},{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (46, 'sbaynard19', 21, 7458, 2461, 'archer', '[]', '[{},{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (47, 'gsawle1a', 65, 4096, 810, 'warrior', '[{},{},{},{},{}]', '[{},{},{},{},{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (48, 'nforde1b', 1, 1241, 1245, 'mage', '[]', '[{}]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (49, 'ddesborough1c', 14, 6464, 69, 'archer', '[{},{},{},{},{}]', '[{},{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (50, 'roffiler1d', 43, 4216, 2243, 'archer', '[{},{},{},{}]', '[{},{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (51, 'lohanlon1e', 96, 5951, 2807, 'warrior', '[]', '[]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (52, 'fmeffan1f', 37, 1216, 661, 'mage', '[{}]', '[{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (53, 'pmclagain1g', 20, 3606, 2737, 'archer', '[{},{},{},{},{}]', '[{},{},{},{},{}]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (54, 'lvalentin1h', 5, 9028, 1939, 'warrior', '[{},{},{},{},{}]', '[{},{},{},{}]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (55, 'ldallemore1i', 28, 8792, 26, 'archer', '[{},{}]', '[]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (56, 'awhittingham1j', 15, 1624, 3300, 'archer', '[{}]', '[]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (57, 'ayegorkov1k', 33, 6022, 1177, 'mage', '[{},{},{},{}]', '[{},{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (58, 'mbreens1l', 46, 5298, 3057, 'mage', '[{}]', '[{},{}]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (59, 'ahugill1m', 93, 3560, 2523, 'warrior', '[{},{}]', '[{},{},{}]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (60, 'hfeldon1n', 81, 1258, 1334, 'warrior', '[{},{},{}]', '[{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (61, 'gowbrick1o', 79, 8519, 1093, 'mage', '[{},{},{}]', '[{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (62, 'egahan1p', 39, 8334, 1086, 'mage', '[{}]', '[{},{},{},{},{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (63, 'liston1q', 87, 725, 856, 'archer', '[{},{},{},{},{}]', '[{},{},{},{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (64, 'ayouthed1r', 89, 6744, 2665, 'mage', '[{},{},{},{},{}]', '[]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (65, 'sstarten1s', 89, 9829, 2188, 'warrior', '[{},{},{}]', '[{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (66, 'fheims1t', 100, 815, 3386, 'archer', '[]', '[{},{},{},{},{}]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (67, 'hgrolle1u', 8, 9835, 1261, 'archer', '[{}]', '[{},{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (68, 'ebrockway1v', 33, 9990, 3510, 'warrior', '[{},{},{},{},{}]', '[{},{},{},{},{}]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (69, 'rwitcher1w', 1, 9628, 3460, 'warrior', '[{},{},{},{},{}]', '[{},{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (70, 'eotridge1x', 17, 1332, 1441, 'mage', '[{},{}]', '[{},{},{},{}]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (71, 'mludman1y', 25, 9651, 2250, 'mage', '[{},{},{},{}]', '[{},{},{},{},{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (72, 'gtuffey1z', 23, 8994, 320, 'archer', '[]', '[{},{},{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (73, 'bjorat20', 54, 1504, 2482, 'mage', '[{},{}]', '[]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (74, 'tmitie21', 15, 6901, 654, 'mage', '[{}]', '[{},{},{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (75, 'candreini22', 81, 7236, 553, 'warrior', '[]', '[{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (76, 'ubingle23', 54, 5045, 430, 'archer', '[{},{},{},{},{}]', '[{},{},{},{},{}]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (77, 'jcorzon24', 80, 244, 1676, 'archer', '[{},{}]', '[{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (78, 'itrubshaw25', 41, 3699, 13, 'archer', '[{},{},{},{},{}]', '[{},{},{},{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (79, 'plorryman26', 76, 6956, 2375, 'mage', '[{}]', '[{},{},{},{},{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (80, 'bowlner27', 87, 2102, 1479, 'archer', '[{},{}]', '[{},{},{},{},{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (81, 'alamminam28', 37, 2985, 2824, 'mage', '[{},{},{},{},{}]', '[]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (82, 'gtock29', 93, 4256, 410, 'mage', '[{}]', '[{},{},{},{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (83, 'jduggan2a', 81, 8268, 1525, 'archer', '[{},{},{},{}]', '[{},{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (84, 'santonowicz2b', 76, 6050, 2848, 'warrior', '[{},{}]', '[{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (85, 'jcromer2c', 12, 6660, 2422, 'warrior', '[{},{},{}]', '[]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (86, 'ostollwerk2d', 30, 1391, 900, 'mage', '[{},{},{},{}]', '[{},{},{},{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (87, 'smaccollom2e', 66, 7548, 1348, 'warrior', '[{}]', '[{},{},{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (88, 'opetrichat2f', 37, 9796, 448, 'mage', '[{},{}]', '[{},{},{},{},{}]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (89, 'rhalbeard2g', 5, 1010, 173, 'warrior', '[{},{}]', '[{},{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (90, 'vsarfati2h', 95, 4540, 1953, 'warrior', '[{}]', '[{},{}]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (91, 'sipsgrave2i', 91, 2277, 2732, 'warrior', '[{}]', '[{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (92, 'llapworth2j', 30, 7587, 2621, 'archer', '[{},{},{},{}]', '[{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (93, 'mmalec2k', 59, 6992, 2704, 'archer', '[]', '[]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (94, 'kcowup2l', 39, 8692, 2017, 'archer', '[{}]', '[{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (95, 'aferrolli2m', 88, 9828, 2828, 'archer', '[{},{}]', '[{},{},{},{}]', 'guild2');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (96, 'tmckernan2n', 81, 1981, 2588, 'warrior', '[]', '[{},{},{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (97, 'sbabb2o', 57, 5441, 2395, 'warrior', '[{},{},{},{},{}]', '[{},{},{},{},{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (98, 'klennon2p', 59, 2714, 1535, 'mage', '[{},{}]', '[{}]', 'guild1');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (99, 'stheakston2q', 28, 5250, 2371, 'mage', '[{},{},{}]', '[{},{},{}]', 'none');
insert into testdata (player_id, username, level, score, game_duration, character_class, inventory, achievements, guild) values (100, 'ccockshoot2r', 27, 4553, 1326, 'mage', '[{}]', '[{},{},{}]', 'none');